language: python
env:
  global:
    - LD_PRELOAD=libSegFault.so
    - SEGFAULT_SIGNALS=all
    - LANG=en_US.UTF-8
    - TWINE_USERNAME=ionel
matrix:
  include:
    - python: '3.6'
      env:
        - TOXENV=check
    - python: '3.6'
      env:
        - TOXENV=docs
    - os: osx
      osx_image: xcode11
      language: generic
      env:
        - TOXENV=py27-cover
    - env:
        - TOXENV=py27-cover,codecov,extension-coveralls,coveralls
      python: '2.7'
      arch: arm64
    - env:
        - TOXENV=py27-cover,codecov,extension-coveralls,coveralls
      python: '2.7'
      arch: amd64
    - os: osx
      osx_image: xcode11
      language: generic
      env:
        - TOXENV=py27-nocov
        - WHEEL_PATH=.tox/dist
    - env:
        - TOXENV=py27-nocov
        - WHEEL_MANYLINUX_TAG=manylinux2014-arm
        - WHEEL_MANYLINUX_PYTHON=cp27
        - WHEEL_PATH=wheelhouse
      python: '2.7'
      arch: arm64
    - env:
        - TOXENV=py27-nocov
        - WHEEL_MANYLINUX_TAG=manylinux1
        - WHEEL_MANYLINUX_PYTHON=cp27
        - WHEEL_PATH=wheelhouse
      python: '2.7'
      arch: amd64
    - env:
        - TOXENV=py35-cover,codecov,extension-coveralls,coveralls
      python: '3.5'
      arch: arm64
    - env:
        - TOXENV=py35-cover,codecov,extension-coveralls,coveralls
      python: '3.5'
      arch: amd64
    - env:
        - TOXENV=py35-nocov
        - WHEEL_MANYLINUX_TAG=manylinux2014-arm
        - WHEEL_MANYLINUX_PYTHON=cp35
        - WHEEL_PATH=wheelhouse
      python: '3.5'
      arch: arm64
    - env:
        - TOXENV=py35-nocov
        - WHEEL_MANYLINUX_TAG=manylinux1
        - WHEEL_MANYLINUX_PYTHON=cp35
        - WHEEL_PATH=wheelhouse
      python: '3.5'
      arch: amd64
    - env:
        - TOXENV=py36-cover,codecov,extension-coveralls,coveralls
      python: '3.6'
      arch: arm64
    - env:
        - TOXENV=py36-cover,codecov,extension-coveralls,coveralls
      python: '3.6'
      arch: amd64
    - env:
        - TOXENV=py36-nocov
        - WHEEL_MANYLINUX_TAG=manylinux2014-arm
        - WHEEL_MANYLINUX_PYTHON=cp36
        - WHEEL_PATH=wheelhouse
      python: '3.6'
      arch: arm64
    - env:
        - TOXENV=py36-nocov
        - WHEEL_MANYLINUX_TAG=manylinux1
        - WHEEL_MANYLINUX_PYTHON=cp36
        - WHEEL_PATH=wheelhouse
      python: '3.6'
      arch: amd64
    - env:
        - TOXENV=py37-cover,codecov,extension-coveralls,coveralls
      python: '3.7'
      arch: arm64
    - env:
        - TOXENV=py37-cover,codecov,extension-coveralls,coveralls
      python: '3.7'
      arch: amd64
    - env:
        - TOXENV=py37-nocov
        - WHEEL_MANYLINUX_TAG=manylinux2014-arm
        - WHEEL_MANYLINUX_PYTHON=cp37
        - WHEEL_PATH=wheelhouse
      python: '3.7'
      arch: arm64
    - env:
        - TOXENV=py37-nocov
        - WHEEL_MANYLINUX_TAG=manylinux1
        - WHEEL_MANYLINUX_PYTHON=cp37
        - WHEEL_PATH=wheelhouse
      python: '3.7'
      arch: amd64
    - os: osx
      osx_image: xcode11
      language: generic
      env:
        - TOXENV=py38-cover
    - env:
        - TOXENV=py38-cover,codecov,extension-coveralls,coveralls
      python: '3.8'
      arch: arm64
    - env:
        - TOXENV=py38-cover,codecov,extension-coveralls,coveralls
      python: '3.8'
      arch: amd64
    - os: osx
      osx_image: xcode11
      language: generic
      env:
        - TOXENV=py38-nocov
        - WHEEL_PATH=.tox/dist
    - env:
        - TOXENV=py38-nocov
        - WHEEL_MANYLINUX_TAG=manylinux2014-arm
        - WHEEL_MANYLINUX_PYTHON=cp38
        - WHEEL_PATH=wheelhouse
      python: '3.8'
      arch: arm64
    - env:
        - TOXENV=py38-nocov
        - WHEEL_MANYLINUX_TAG=manylinux1
        - WHEEL_MANYLINUX_PYTHON=cp38
        - WHEEL_PATH=wheelhouse
      python: '3.8'
      arch: amd64
before_install:
  - python --version
  - uname -a
  - lsb_release -a || true
  - |
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      brew update-reset
      [[ $TOXENV =~ py3 ]] && brew upgrade python
      [[ $TOXENV =~ py2 ]] && brew install python@2
      export PATH="/usr/local/opt/python/libexec/bin:${PATH}"
    fi
install:
  - python -mpip install --progress-bar=off twine tox-wheel -rci/requirements.txt
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
script:
  - |
    (
    set -eux
    if [[ -n ${WHEEL_MANYLINUX_TAG:-} ]]; then
      docker run --rm --user $UID -itv $(pwd):/code ionelmc/manylinux:$WHEEL_MANYLINUX_TAG $WHEEL_MANYLINUX_PYTHON
      tox --installpkg $WHEEL_PATH/*.whl -v
    else
      tox -v
    fi
    if [[ -n ${WHEEL_PATH:-} ]]; then
      twine upload --repository-url https://test.pypi.org/legacy/ --skip-existing $WHEEL_PATH/*.whl
    fi
    )
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: never
    on_failure: always
