version: '{branch}-{build}'
build: off
environment:
  global:
    WITH_COMPILER: 'cmd /E:ON /V:ON /C .\ci\appveyor-with-compiler.cmd'
  matrix:
    - TOXENV: '3.5-nocover'
      TOXPYTHON: 'C:\Python35-x64\python.exe'
      PYTHON_HOME: 'C:\Python35-x64'
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '64'
init:
  - ps: 'echo $env:TOXENV'
  - ps: 'ls C:\Python*'
install:
  - python -u ci\appveyor-bootstrap.py
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\easy_install --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\tox --version'
test_script:
  - '%WITH_COMPILER% %PYTHON_HOME%\Scripts\tox'
after_test:
  - 'IF "%TOXENV:~-8,8%" == "-nocover" %WITH_COMPILER% %TOXPYTHON% setup.py bdist_wheel'
artifacts:
  - path: 'dist\*'
on_failure:
  - ps: 'dir env:'
  - ps: 'get-content .tox\*\log\*'
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
