on: [push, pull_request]
jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'check'
            python: '3.9'
            toxpython: 'python3.9'
            tox_env: 'check'
            os: 'ubuntu-latest'
          - name: 'docs'
            python: '3.9'
            toxpython: 'python3.9'
            tox_env: 'docs'
            os: 'ubuntu-latest'
          - name: 'py36-cover (ubuntu)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-cover,codecov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'py36-cover (windows)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-cover,codecov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'windows-latest'
          - name: 'py36-cover (macos)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-cover,codecov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'macos-latest'
          - name: 'py36-nocov (ubuntu)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-nocov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'py36-nocov (windows)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-nocov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'windows-latest'
          - name: 'py36-nocov (macos)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-nocov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'macos-latest'
          - name: 'py37-cover (ubuntu)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-cover,codecov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'py37-cover (windows)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-cover,codecov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'windows-latest'
          - name: 'py37-cover (macos)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-cover,codecov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'macos-latest'
          - name: 'py37-nocov (ubuntu)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-nocov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'py37-nocov (windows)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-nocov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'windows-latest'
          - name: 'py37-nocov (macos)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-nocov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'macos-latest'
          - name: 'py38-cover (ubuntu)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-cover,codecov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'py38-cover (windows)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-cover,codecov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'windows-latest'
          - name: 'py38-cover (macos)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-cover,codecov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'macos-latest'
          - name: 'py38-nocov (ubuntu)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-nocov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'py38-nocov (windows)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-nocov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'windows-latest'
          - name: 'py38-nocov (macos)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-nocov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'macos-latest'
          - name: 'py39-cover (ubuntu)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-cover,codecov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'py39-cover (windows)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-cover,codecov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'windows-latest'
          - name: 'py39-cover (macos)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-cover,codecov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'macos-latest'
          - name: 'py39-nocov (ubuntu)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-nocov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'py39-nocov (windows)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-nocov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'windows-latest'
          - name: 'py39-nocov (macos)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-nocov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'macos-latest'
          - name: 'py310-cover (ubuntu)'
            python: '3.10'
            toxpython: 'python3.10'
            python_arch: 'x64'
            tox_env: 'py310-cover,codecov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'py310-cover (windows)'
            python: '3.10'
            toxpython: 'python3.10'
            python_arch: 'x64'
            tox_env: 'py310-cover,codecov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'windows-latest'
          - name: 'py310-cover (macos)'
            python: '3.10'
            toxpython: 'python3.10'
            python_arch: 'x64'
            tox_env: 'py310-cover,codecov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'macos-latest'
          - name: 'py310-nocov (ubuntu)'
            python: '3.10'
            toxpython: 'python3.10'
            python_arch: 'x64'
            tox_env: 'py310-nocov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'py310-nocov (windows)'
            python: '3.10'
            toxpython: 'python3.10'
            python_arch: 'x64'
            tox_env: 'py310-nocov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'windows-latest'
          - name: 'py310-nocov (macos)'
            python: '3.10'
            toxpython: 'python3.10'
            python_arch: 'x64'
            tox_env: 'py310-nocov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'macos-latest'
          - name: 'pypy37-cover (ubuntu)'
            python: 'pypy-3.7'
            toxpython: 'pypy3.7'
            python_arch: 'x64'
            tox_env: 'pypy37-cover,codecov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'pypy37-cover (windows)'
            python: 'pypy-3.7'
            toxpython: 'pypy3.7'
            python_arch: 'x64'
            tox_env: 'pypy37-cover,codecov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'windows-latest'
          - name: 'pypy37-cover (macos)'
            python: 'pypy-3.7'
            toxpython: 'pypy3.7'
            python_arch: 'x64'
            tox_env: 'pypy37-cover,codecov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'macos-latest'
          - name: 'pypy37-nocov (ubuntu)'
            python: 'pypy-3.7'
            toxpython: 'pypy3.7'
            python_arch: 'x64'
            tox_env: 'pypy37-nocov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'pypy37-nocov (windows)'
            python: 'pypy-3.7'
            toxpython: 'pypy3.7'
            python_arch: 'x64'
            tox_env: 'pypy37-nocov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'windows-latest'
          - name: 'pypy37-nocov (macos)'
            python: 'pypy-3.7'
            toxpython: 'pypy3.7'
            python_arch: 'x64'
            tox_env: 'pypy37-nocov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'macos-latest'
          - name: 'pypy38-cover (ubuntu)'
            python: 'pypy-3.8'
            toxpython: 'pypy3.8'
            python_arch: 'x64'
            tox_env: 'pypy38-cover,codecov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'pypy38-cover (windows)'
            python: 'pypy-3.8'
            toxpython: 'pypy3.8'
            python_arch: 'x64'
            tox_env: 'pypy38-cover,codecov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'windows-latest'
          - name: 'pypy38-cover (macos)'
            python: 'pypy-3.8'
            toxpython: 'pypy3.8'
            python_arch: 'x64'
            tox_env: 'pypy38-cover,codecov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'macos-latest'
          - name: 'pypy38-nocov (ubuntu)'
            python: 'pypy-3.8'
            toxpython: 'pypy3.8'
            python_arch: 'x64'
            tox_env: 'pypy38-nocov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'pypy38-nocov (windows)'
            python: 'pypy-3.8'
            toxpython: 'pypy3.8'
            python_arch: 'x64'
            tox_env: 'pypy38-nocov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'windows-latest'
          - name: 'pypy38-nocov (macos)'
            python: 'pypy-3.8'
            toxpython: 'pypy3.8'
            python_arch: 'x64'
            tox_env: 'pypy38-nocov'
            cibw_arch: 'native'
            cibw_build: false
            os: 'macos-latest'
    steps:
    - uses: docker/setup-qemu-action@v1
      if: matrix.cibw_arch == 'aarch64'
      with:
        platforms: arm64
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.python_arch }}
    - name: install dependencies
      run: |
        python -mpip install --progress-bar=off twine tox cibuildwheel -r ci/requirements.txt
        virtualenv --version
        pip --version
        tox --version
        pip list --format=freeze
    - name: install dependencies (gdb)
      if: >
        !matrix.cibw_build && matrix.os == 'ubuntu'
      run: >
        sudo apt-get install gdb
    - name: cibw build and test
      if: matrix.cibw_build
      run: cibuildwheel
      env:
        TOXPYTHON: '${{ matrix.toxpython }}'
        CIBW_ARCHS: '${{ matrix.cibw_arch }}'
        CIBW_BUILD: '${{ matrix.cibw_build }}'
        CIBW_BUILD_VERBOSITY: '3'
        CIBW_TEST_REQUIRES: >
          tox
          tox-direct
        CIBW_TEST_COMMAND: >
          cd {project} &&
          tox --skip-pkg-install --direct-yolo -e ${{ matrix.tox_env }} -v
        CIBW_TEST_COMMAND_WINDOWS: >
          cd /d {project} &&
          tox --skip-pkg-install --direct-yolo -e ${{ matrix.tox_env }} -v
    - name: regular build and test
      env:
        TOXPYTHON: '${{ matrix.toxpython }}'
      if: >
        !matrix.cibw_build
      run: >
        tox -e ${{ matrix.tox_env }} -v
    - name: check wheel
      if: matrix.cibw_build
      run: twine check wheelhouse/*.whl
    - name: upload wheel
      uses: actions/upload-artifact@v2
      if: matrix.cibw_build
      with:
        path: wheelhouse/*.whl
